In [38]:
import pandas as pd

In [39]:
#Loading the dataset
df=pd.read_csv('/content/drive/MyDrive/netflix_titles.csv')
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, Jos√© Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [40]:
#Dataset exploring
print("\n Shape Of the dataframe")
print(df.shape)
print("\n Data types of the columns")
display(df.dtypes)
#Dataset Information
print("\n Dataset Information")
print(df.info())

 Shape Of the dataframe
(8807, 12)

 Data types of the columns

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

 Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB
None

In [41]:
#glance of numerical data
print("\n Glance of numerical data")
print(df.describe())
#glance of categorical data
print("\n Glance of categorical data")
for col in df.select_dtypes(include=['object']).columns:
    print(f"\nColumn: {col}")
    print(f"Unique values: {df[col].unique()[:20]}") # Limiting to first 20 for brevity
    print(f"Value counts:\n{df[col].value_counts()[:10]}")

 Glance of numerical data
       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

 Glance of categorical data

Column: show_id
Unique values: ['s1' 's2' 's3' 's4' 's5' 's6' 's7' 's8' 's9' 's10' 's11' 's12' 's13'
 's14' 's15' 's16' 's17' 's18' 's19' 's20']
Value counts:
show_id
s8807    1
s1       1
s2       1
s3       1
s4       1
s5       1
s6       1
s8791    1
s8790    1
s8789    1
Name: count, dtype: int64

Column: type
Unique values: ['Movie' 'TV Show']
Value counts:
type
Movie      6131
TV Show    2676
Name: count, dtype: int64

Column: title
Unique values: ['Dick Johnson Is Dead' 'Blood & Water' 'Ganglands'
 'Jailbirds New Orleans' 'Kota Factory' 'Midnight Mass'
 'My Little Pony: A New Generation' 'Sankofa'
 'The Great British Baking Show' 'The Starling'
 'Vendetta: Truth, Lies and The Mafia' 'Bangkok Breaking' 'Je Suis Karl'
 'Confessions of an Invisible Girl' 'Crime Stories: India Detectives'
 'Dear White People' "Europe's Most Dangerous Man: Otto Skorzeny in Spain"
 'Falsa identidad' 'Intrusion' 'Jaguar']
Value counts:
title
Zubaan                           1
Dick Johnson Is Dead             1
Blood & Water                    1
Ganglands                        1
Jailbirds New Orleans            1
Kota Factory                     1
Midnight Mass                    1
You Don't Mess with the Zohan    1
You Changed My Life              1
You Carry Me                     1
Name: count, dtype: int64

Column: director
Unique values: ['Kirsten Johnson' nan 'Julien Leclercq' 'Mike Flanagan'
 'Robert Cullen, Jos√© Luis Ucha' 'Haile Gerima' 'Andy Devonshire'
 'Theodore Melfi' 'Kongkiat Komesiri' 'Christian Schwochow'
 'Bruno Garotti' 'Pedro de Echave Garc√≠a, Pablo Azor√≠n Williams'
 'Adam Salky' 'Olivier Megaton' 'K.S. Ravikumar' 'Alex Woo, Stanley Moore'
 'S. Shankar' 'Rajiv Menon' 'Dennis Dugan' 'Scott Stewart']
Value counts:
director
Rajiv Chilaka             19
Ra√∫l Campos, Jan Suter    18
Suhas Kadav               16
Marcus Raboy              16
Jay Karas                 14
Cathy Garcia-Molina       13
Martin Scorsese           12
Youssef Chahine           12
Jay Chapman               12
Steven Spielberg          11
Name: count, dtype: int64

Column: cast
Unique values: [nan
 'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng'
 'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera'
 'Mayur More, Jitendra Kumar, Ranjan Raj, Alam Khan, Ahsaas Channa, Revathi Pillai, Urvi Singh, Arun Kumar'
 'Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver'
 'Vanessa Hudgens, Kimiko Glenn, James Marsden, Sofia Carson, Liza Koshy, Ken Jeong, Elizabeth Perkins, Jane Krakowski, Michael McKean, Phil LaMarr'
 'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri'
 'Mel Giedroyc, Sue Perkins, Mary Berry, Paul Hollywood'
 "Melissa McCarthy, Chris O'Dowd, Kevin Kline, Timothy Olyphant, Daveed Diggs, Skyler Gisondo, Laura Harrier, Rosalind Chao, Kimberly Quinn, Loretta Devine, Ravi Kapoor"
 'Sukollawat Kanarot, Sushar Manaying, Pavarit Mongkolpisit, Sahajak Boonthanakit, Suthipongse Thatphithakkul, Bhasaworn Bawronkirati, Daweerit Chullasapya, Waratthaya Wongchayaporn, Kittiphoom Wongpentak, Abhicha Thanachanun, Nophand Boonyai, Kittipong Khamsat, Arisara Wongchalee, Jaytiya Naiwattanakul, Pantipa Arunwattanachai, Panupan Jantanawong, Kungtap Saelim, Phumphat Chartsuriyakiat, Issara Veranitinunt, Keerati Sivakuae, Panjai Sirisuwan, Supranee Charoenpol, Suda Chuenban, Visaka Banhansupavat, Pitchatorn Santinatornkul'
 'Luna Wedler, Jannis Niew√∂hner, Milan Peschel, Edin Hasanoviƒá, Anna Fialov√°, Marlon Boess, Victor Boccard, Fleur Geffrier, Aziz Dyab, M√©lanie Fouch√©, Elizaveta Maximov√°'
 'Klara Castanho, Lucca Picon, J√∫lia Gomes, Marcus Bessa, Kiria Malheiros, Fernanda Concon, Gabriel Lima, Caio Cabral, Leonardo Cidade, Jade Cardozo'
 'Logan Browning, Brandon P. Bell, DeRon Horton, Antoinette Robertson, John Patrick Amedori, Ashley Blaine Featherson, Marque Richardson, Giancarlo Esposito'
 'Luis Ernesto Franco, Camila Sodi, Sergio Goyri, Samadhi Zendejas, Eduardo Y√°√±ez, Sonya Smith, Alejandro Camacho, Azela Robinson, Uriel del Toro, G√©raldine Baz√°n, Gabriela Roel, Marcus Ornellas'
 'Freida Pinto, Logan Marshall-Green, Robert John Burke, Megan Elisabeth Kelly, Sarah Minnich, Hayes Hargrove, Mark Sivertsen, Brandon Fierro, Antonio Valles, Clint Obenchain'
 'Blanca Su√°rez, Iv√°n Marcos, √ìscar Casas, Adri√°n Lastra, Francesc Garrido, Stefan Weinert, Julia M√∂ller, Alicia Chojnowski'
 'Engin Altan D√ºzyatan, Serdar G√∂khan, H√ºlya Darcan, Kaan Ta≈üaner, Esra Bilgi√ß, Osman Soykut, Serdar Deniz, Cengiz Co≈ükun, Reshad Strik, Hande Suba≈üƒ±'
 'Kamal Hassan, Meena, Gemini Ganesan, Heera Rajgopal, Nassar, S.P. Balasubrahmanyam'
 'Maisie Benson, Paul Killam, Kerry Gudjohnsen, AC Lim'
 'Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi, Nassar']
Value counts:
cast
David Attenborough                                                                                                        19
Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jigna Bhardwaj, Rajesh Kava, Mousam, Swapnil                                   14
Samuel West                                                                                                               10
Jeff Dunham                                                                                                                7
Michela Luci, Jamie Watson, Eric Peterson, Anna Claire Bartlam, Nicolas Aqui, Cory Doran, Julie Lemieux, Derek McGrath     6
David Spade, London Hughes, Fortune Feimster                                                                               6
Craig Sechler                                                                                                              6
Kevin Hart                                                                                                                 6
Bill Burr                                                                                                                  5
Jim Gaffigan                                                                                                               5
Name: count, dtype: int64

Column: country
Unique values: ['United States' 'South Africa' nan 'India'
 'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia'
 'United Kingdom' 'Germany, Czech Republic' 'Mexico' 'Turkey' 'Australia'
 'United States, India, France' 'Finland' 'China, Canada, United States'
 'South Africa, United States, Japan' 'Nigeria' 'Japan'
 'Spain, United States' 'France' 'Belgium' 'United Kingdom, United States']
Value counts:
country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: count, dtype: int64

Column: date_added
Unique values: ['September 25, 2021' 'September 24, 2021' 'September 23, 2021'
 'September 22, 2021' 'September 21, 2021' 'September 20, 2021'
 'September 19, 2021' 'September 17, 2021' 'September 16, 2021'
 'September 15, 2021' 'September 14, 2021' 'September 11, 2021'
 'September 10, 2021' 'September 9, 2021' 'September 8, 2021'
 'September 7, 2021' 'September 6, 2021' 'September 5, 2021'
 'September 4, 2021' 'September 3, 2021']
Value counts:
date_added
January 1, 2020      109
November 1, 2019      89
March 1, 2018         75
December 31, 2019     74
October 1, 2018       71
July 1, 2021          60
October 1, 2019       60
November 1, 2018      60
September 1, 2021     56
January 1, 2018       52
Name: count, dtype: int64

Column: rating
Unique values: ['PG-13' 'TV-MA' 'PG' 'TV-14' 'TV-PG' 'TV-Y' 'TV-Y7' 'R' 'TV-G' 'G'
 'NC-17' '74 min' '84 min' '66 min' 'NR' nan 'TV-Y7-FV' 'UR']
Value counts:
rating
TV-MA    3207
TV-14    2160
TV-PG     863
R         799
PG-13     490
TV-Y7     334
TV-Y      307
PG        287
TV-G      220
NR         80
Name: count, dtype: int64

Column: duration
Unique values: ['90 min' '2 Seasons' '1 Season' '91 min' '125 min' '9 Seasons' '104 min'
 '127 min' '4 Seasons' '67 min' '94 min' '5 Seasons' '161 min' '61 min'
 '166 min' '147 min' '103 min' '97 min' '106 min' '111 min']
Value counts:
duration
1 Season     1793
2 Seasons     425
3 Seasons     199
90 min        152
97 min        146
94 min        146
93 min        146
91 min        144
95 min        137
96 min        130
Name: count, dtype: int64

Column: listed_in
Unique values: ['Documentaries' 'International TV Shows, TV Dramas, TV Mysteries'
 'Crime TV Shows, International TV Shows, TV Action & Adventure'
 'Docuseries, Reality TV'
 'International TV Shows, Romantic TV Shows, TV Comedies'
 'TV Dramas, TV Horror, TV Mysteries' 'Children & Family Movies'
 'Dramas, Independent Movies, International Movies'
 'British TV Shows, Reality TV' 'Comedies, Dramas'
 'Crime TV Shows, Docuseries, International TV Shows'
 'Dramas, International Movies' 'Children & Family Movies, Comedies'
 'British TV Shows, Crime TV Shows, Docuseries' 'TV Comedies, TV Dramas'
 'Documentaries, International Movies'
 'Crime TV Shows, Spanish-Language TV Shows, TV Dramas' 'Thrillers'
 'International TV Shows, Spanish-Language TV Shows, TV Action & Adventure'
 'International TV Shows, TV Action & Adventure, TV Dramas']
Value counts:
listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
Kids' TV                                            220
Children & Family Movies                            215
Children & Family Movies, Comedies                  201
Documentaries, International Movies                 186
Dramas, International Movies, Romantic Movies       180
Name: count, dtype: int64

Column: description
Unique values: ['As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.'
 'After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.'
 'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.'
 'Feuds, flirtations and toilet talk go down among the incarcerated women at the Orleans Justice Center in New Orleans on this gritty reality series.'
 'In a city of coaching centers known to train India‚Äôs finest collegiate minds, an earnest but unexceptional student and his friends navigate campus life.'
 'The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe.'
 "Equestria's divided. But a bright-eyed hero believes Earth Ponies, Pegasi and Unicorns should be pals ‚Äî and, hoof to heart, she‚Äôs determined to prove it."
 'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.'
 "A talented batch of amateur bakers face off in a 10-week competition, whipping up their best dishes in the hopes of being named the U.K.'s best."
 "A woman adjusting to life after a loss contends with a feisty bird that's taken over her garden ‚Äî and a husband who's struggling to find a way forward."
 'Sicily boasts a bold "Anti-Mafia" coalition. But what happens when those trying to bring down organized crime are accused of being criminals themselves?'
 'Struggling to earn a living in Bangkok, a man joins an emergency rescue service and realizes he must unravel a citywide conspiracy.'
 'After most of her family is murdered in a terrorist bombing, a young woman is unknowingly lured into joining the very group that killed them.'
 "When the clever but socially-awkward Tet√™ joins a new school, she'll do anything to fit in. But the queen bee among her classmates has other ideas."
 'Cameras following Bengaluru police on the job offer a rare glimpse into the complex and challenging inner workings of four major crime investigations.'
 'Students of color navigate the daily slights and slippery politics of life at an Ivy League college that\'s not nearly as "post-racial" as it thinks.'
 'Declassified documents reveal the post-WWII life of Otto Skorzeny, a close Hitler ally who escaped to Spain and became an adviser to world presidents.'
 'Strangers Diego and Isabel flee their home in Mexico and pretend to be a married couple to escape his drug-dealing enemies and her abusive husband.'
 'After a deadly home invasion at a couple‚Äôs new dream house, the traumatized wife searches for answers ‚Äî and learns the real danger is just beginning.'
 'In the 1960s, a Holocaust survivor joins a group of self-trained spies who seek justice against Nazis fleeing to Spain to hide after WWII.']
Value counts:
description
Paranormal activity at a lush, abandoned property alarms a group eager to redevelop the site, but the eerie events may not be as unearthly as they think.    4
A surly septuagenarian gets another chance at her 20s after having her photo snapped at a studio that magically takes 50 years off her life.                 3
Multiple women report their husbands as missing but when it appears they are looking for the same man, a police officer traces their cryptic connection.     3
Challenged to compose 100 songs before he can marry the girl he loves, a tortured but passionate singer-songwriter embarks on a poignant musical journey.    3
A scheming matriarch plots to cut off her disabled stepson and his wife from the family fortune, creating a division within the clan.                        2
As a series of murders hit close to home, a video game designer with post-traumatic stress must confront her demons, or risk becoming their victim.          2
When Elastigirl gets recruited for a high-profile crime-fighting mission, Mr. Incredible takes on his toughest assignment ever: full-time parenting.         2
Secrets bubble to the surface after a sensual encounter and an unforeseen crime entangle two friends and a woman caught between them.                        2
From controversial cartoonist to powerful Mumbai politician, this biopic maps the meteoric rise of far-right Shiv Sena party founder, Bal Thackeray.         2
When pretty new neighbor Seema falls for their shy roommate Sid, jealous womanizers Omi and Jai plot to break up the new lovebirds.                          2
Name: count, dtype: int64

In [43]:
#Missing Values
missing_values=df.isnull().sum()
missing_percentage=(missing_values/len(df))*100
missing_info=pd.DataFrame({"Missing Values":missing_values,"Missing_percentage":missing_percentage})
display(missing_info)
#Duplicate Rows
duplicate_rows = df[df.duplicated()]
num_duplicates = len(duplicate_rows)
print(f"\nNumber of duplicate rows: {num_duplicates}")
print("\nDuplicate Rows:")
print(duplicate_rows)
display(df.columns)

              Missing Values  Missing_percentage
show_id                    0            0.000000
type                       0            0.000000
title                      0            0.000000
director                2634           29.908028
cast                     825            9.367549
country                  831            9.435676
date_added                10            0.113546
release_year               0            0.000000
rating                     4            0.045418
duration                   3            0.034064
listed_in                  0            0.000000
description                0            0.000000

Number of duplicate rows: 0

Duplicate Rows:
Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [47]:
# 1. Handle missing values correctly
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')

# 2. Smart filling for date
movie_common_date = df[df['type'] == 'Movie']['date_added'].mode()[0]
tvshow_common_date = df[df['type'] == 'TV Show']['date_added'].mode()[0]

def smart_fill(row):
    if pd.isnull(row['date_added']):
        if row['type'] == 'Movie':
            return movie_common_date
        else:
            return tvshow_common_date
    else:
        return row['date_added']

df['date_added'] = df.apply(smart_fill, axis=1)

# 3. Fill Rating and Duration
df['rating'] = df['rating'].fillna('Not Rated')

if not df['duration'].mode().empty:
    df['duration'] = df['duration'].fillna(df['duration'].mode()[0])
else:
    df['duration'] = df['duration'].fillna('Unknown')

# 4. Data type conversions
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['release_year'] = df['release_year'].astype('int64')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [48]:
# Changing data types
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')  # small letters
df['release_year'] = df['release_year'].astype('int64')               # small letters

display(df.dtypes)

show_id                 object
type                    object
title                   object
director                object
cast                    object
country                 object
date_added      datetime64[ns]
release_year             int64
rating                  object
duration                object
listed_in               object
description             object
dtype: object

In [49]:
df.to_csv('/content/drive/MyDrive/netflix_cleaned.csv', index=False)
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...